1290 improve appointments table on mobile devices
chicago-tool-library/circulate pull request #1376
Opened 2024-02-27 12:25 UTC by mdecelle

# What it does

Changes the appointments view from a table layout to a list of cards to make it more friendly for mobile users

# Why it is important

Current appointment list table is truncated and difficult to read on a mobile device

# UI Change Screenshot

Before:
![image](https://github.com/chicago-tool-library/circulate/assets/2738059/318d533a-fe19-44d6-a330-04aa1a5ffadb)
![image](https://github.com/chicago-tool-library/circulate/assets/2738059/786efb9a-fffd-4b47-833b-d64f1dcfd883)

After:
![image](https://github.com/chicago-tool-library/circulate/assets/2738059/ae34d411-280c-4cb8-9237-e68e633d79a7)
![image](https://github.com/chicago-tool-library/circulate/assets/2738059/3f37ec10-1118-478a-b69b-5a93f3ba29a8)

Greyed out completed appointments:
![image](https://github.com/chicago-tool-library/circulate/assets/2738059/282925bf-513e-4dfb-a19c-587b62e95408)
![image](https://github.com/chicago-tool-library/circulate/assets/2738059/04ea1f71-54fe-42d5-b068-e580d7a169d0)

# Implementation notes

Converted the table rows to be individual cards. I would not mind extra scrutiny on the use of inline styles and organization.

Would like to know if the categories that were added is what the user really wants to see (sort of guessed that was a relevant element).

# Your bandwidth for additional changes to this PR

_Please choose one of the following to help the project maintainers provide the appropriate level of support:_

- [x] I have the time and interest to make additional changes to this PR based on feedback.
- [ ] I am interested in feedback but don't need to make the changes myself.
- [ ] I don't have time or interest in making additional changes to this work.
- [ ] Other or not sure (please describe):

2024-03-02 20:00 UTC, jim requested changes
This is huge improvement! I think the categories you used here are the right ones. Another thing that we'd talked about was having the appointment notes in some kind of expandable area or modal, and I think this PR sets us up nicely to do that in the future.

In terms of visual layout, in the desktop view there is a lot of empty space and the "Pickup Items" and "Dropoff Items" headers feel too big compared to the other test. They could probably be just the body text size but bold or something.

If we can tweak the size of that text and make it so that all holds are displayed for an appointment, I think this will be ready to merge. We can also ask the staff if they have feedback, but my thought on that is we can deploy this and then see if they have ideas for further refinement.

2024-03-04 13:02 UTC, mdecelle commented
Updated the screen to reduce header sizes and unnecessary white space. 

Mobile: 
![image](https://github.com/chicago-tool-library/circulate/assets/2738059/0ee0791a-fdae-4ed7-a358-d1f7495e2f26)

Desktop:
![image](https://github.com/chicago-tool-library/circulate/assets/2738059/56663e09-3e90-432c-9898-acc2ab27b033)

2024-03-04 13:22 UTC, mdecelle commented
Reduced white space and added a place for the appointment notes.

Desktop:
![image](https://github.com/chicago-tool-library/circulate/assets/2738059/94c19f6e-5ea9-4f8a-afc9-627d2c4c717e)
![image](https://github.com/chicago-tool-library/circulate/assets/2738059/a3d6b7a2-0984-4d45-a4eb-51383e418ca6)

Mobile:
![image](https://github.com/chicago-tool-library/circulate/assets/2738059/52c325dd-c7e0-4adf-aa3d-f54e5ba5fd64)
![image](https://github.com/chicago-tool-library/circulate/assets/2738059/49186d8a-263f-4f62-868d-ac82074bb32c)

2024-03-10 04:49 UTC, jim approved these changes

2024-03-11 16:23 UTC, phinze approved these changes
Shepherding this to staging today as discussed last week 🚀

2024-03-11 16:23 UTC, merged